services:
  agentmodule:
    build:
      context: .
      dockerfile: docker/agent/Dockerfile
      target: develop
    ports:
      - "50051:50051"
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - .env